const test = require('node:test')
const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const path = require('node:path')
const read = (file) => readFileSync(path.resolve(__dirname, '..', file), 'utf8')
test('staff dashboard uses personal visual components and annual quota only', () => {
  const page = read('app/(dashboard)/page.js')
  const staff = page.slice(page.indexOf('function StaffDashboard'))
  for (const text of ['Sisa Cuti Tahun Ini', 'Notifikasi', 'Status Pengajuan Cuti Terakhir']) assert.ok(staff.includes(text))
  assert.doesNotMatch(staff, /reminder/i, 'STAFF dashboard does not show reminder widgets or events')
  assert.match(staff, /StaffGreeting/)
  assert.match(staff, /code\s*===\s*['"]annual['"]/)
  for (const widget of ['EmployeeTrend', 'ContractStatus', 'AssetDistribution', 'InsightPanel']) assert.ok(!staff.includes(widget))
  assert.match(staff, /staff-theme/)
  const form = read('app/(dashboard)/cuti/saya/ajukan/page.js')
  assert.equal((form.match(/<StaffDatePicker/g) || []).length, 2)
  assert.match(form, /<StaffFileDropzone/)
  assert.match(form, /validateStaffAttachment/)
  assert.match(form, /toast\.success/)
  assert.doesNotMatch(form, /router\.push|window\.location/)
  assert.match(form, /w-full max-w-none/)
  assert.match(form, /md:grid-cols-2/)
})
