var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/kendaraan/pajak/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__998e2b0e._.js")
R.c("server/chunks/ssr/node_modules_next_dist_65e60196._.js")
R.c("server/chunks/ssr/_60102236._.js")
R.c("server/chunks/ssr/[root-of-the-server]__50c38a72._.js")
R.c("server/chunks/ssr/node_modules_next_68438f7c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f9713a08._.js")
R.c("server/chunks/ssr/app_e744e06a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_d4f6ac69._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_(dashboard)_layout_28626e54.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_kendaraan_pajak_page_actions_331a8b25.js")
R.m(36033)
module.exports=R.m(36033).exports
