var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/karyawan/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__4425b18c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_65e60196._.js")
R.c("server/chunks/ssr/_3852ee85._.js")
R.c("server/chunks/ssr/[root-of-the-server]__50c38a72._.js")
R.c("server/chunks/ssr/node_modules_next_68438f7c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f9713a08._.js")
R.c("server/chunks/ssr/app_2fecf24e._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_9bb93703._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_(dashboard)_layout_28626e54.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_karyawan_[id]_page_actions_5a19a9cb.js")
R.m(35626)
module.exports=R.m(35626).exports
